# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_downloader.rb"
class Genderize < Formula
  desc "Example CLI tool written in Go"
  homepage ""
  version "1.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/karlderkaefer/homebrew-golang-cli-example/releases/download/v1.0.2/genderize_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "11a707f9878700748c1735ac7a01e312481992264c6270514ef956cdf03d8e1b"

      def install
        bin.install "genderize"
      end
    end
    on_arm do
      url "https://github.com/karlderkaefer/homebrew-golang-cli-example/releases/download/v1.0.2/genderize_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bda7d191fc789ac8cea76cfa7aea8b350c047790ddfdfda5450e7326313c84d1"

      def install
        bin.install "genderize"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/karlderkaefer/homebrew-golang-cli-example/releases/download/v1.0.2/genderize_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "8e85330b98cfab41bb6b93775e904ab189d85b78cdfee1cbeab7153d151ed9e9"

        def install
          bin.install "genderize"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/karlderkaefer/homebrew-golang-cli-example/releases/download/v1.0.2/genderize_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "7e01a924ba07afb3387c5c070c3a798f9ae8b11a5efd68d49a608bfa216d0b44"

        def install
          bin.install "genderize"
        end
      end
    end
  end

  test do
    system "#{bin}/genderize -v"
  end
end
